### Read the dataset, show its head, shape and description

In [4]:
# Imports
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

# Variables
file_name= 'AirQualityUCI.csv'
random_state = 42
np.random.seed(random_state)

df = pd.read_csv(file_name, sep=';')
df.head()

,Date,Time,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN,NaN
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN,NaN
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN,NaN
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN,NaN
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN,NaN

In [5]:
df.shape

(9471, 18)

In [6]:
df.describe()

,X00,X01,X02,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12,X13,X14,X15
count,7765.000000,8991.000000,914.000000,9357.000000,8991.000000,7718.000000,8991.000000,7715.000000,8991.000000,8991.000000,8991.000000,8991.000000,8991.000000,0.0,0.0,0.0
mean,2.127521,1099.833166,218.811816,9.688704,939.153376,246.896735,835.493605,113.091251,1456.264598,1022.906128,18.317829,49.234201,1.025530,NaN,NaN,NaN
std,1.463171,217.080037,204.459921,7.559785,266.831429,212.979168,256.817320,48.370108,346.206794,398.484288,8.832116,17.316892,0.403813,NaN,NaN,NaN
min,0.000000,647.000000,7.000000,0.000000,383.000000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.200000,0.184700,NaN,NaN,NaN
25%,1.000000,937.000000,67.000000,4.000000,734.500000,98.000000,658.000000,78.000000,1227.000000,731.500000,11.800000,35.800000,0.736800,NaN,NaN,NaN
50%,1.800000,1063.000000,150.000000,7.900000,909.000000,180.000000,806.000000,109.000000,1463.000000,963.000000,17.800000,49.600000,0.995400,NaN,NaN,NaN
75%,2.900000,1231.000000,297.000000,13.600000,1116.000000,326.000000,969.500000,142.000000,1674.000000,1273.500000,24.400000,62.500000,1.313700,NaN,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN,NaN

### Eliminate totally null columns and totally null rows, eliminate columns with less than 1/3 of non null values; fill the remaining NaN values with the mean of the column

In [17]:
dfclean=df.dropna(how='all')
dfclean=dfclean.dropna(thresh=(len(dfclean)*1/3),axis=1)
dfclean.shape
print(f"NaN rimanenti dopo riempimento: {dfclean.isnull().sum().sum()}")

NaN rimanenti dopo riempimento: 7801

In [81]:

#Filling remaining NaN values with the mean of the column
numericcols = dfclean.select_dtypes('number').columns
dfclean[numericcols] = dfclean[numericcols].fillna(dfclean[numericcols].mean())

In [82]:
dfclean.shape

(9357, 14)

In [86]:
dfclean.head()

,Date,Time,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
0,10/03/2004,18.00.00,2.6,1360.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [87]:
print(f"NaN rimanenti dopo riempimento: {dfclean.isnull().sum().sum()}")

NaN rimanenti dopo riempimento: 0

### Drop Time, convert Date from string to datetime and group by Date using mean as aggregate function

In [88]:
from datetime import date
dffinal=dfclean.drop('Time',axis=1)
#Converting 'Date' from string to datetime
dffinal['Date'] = pd.to_datetime(dffinal['Date'],format="%d/%m/%Y")
dffinal.head()

,Date,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
0,2004-03-10,2.6,1360.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,2004-03-10,2.0,1292.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,2004-03-10,2.2,1402.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,2004-03-10,2.2,1376.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,2004-03-10,1.6,1272.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [89]:
df_grouped = dffinal.groupby('Date').mean()
df_grouped.head()

,X00,X01,X03,X04,X05,X06,X07,X08,X09,X10,X11,X12
Date,,,,,,,,,,,,
2004-03-10,1.966667,1316.500000,8.450000,912.333333,132.000000,1167.333333,108.833333,1545.500000,1096.000000,12.033333,54.900000,0.765633
2004-03-11,2.234480,1244.166667,7.979167,851.958333,148.662364,1277.250000,100.420469,1522.833333,885.250000,9.837500,64.075000,0.775767
2004-03-12,2.748127,1281.666667,12.129167,1008.291667,179.824728,1101.875000,116.007604,1627.291667,1084.375000,11.287500,51.095833,0.663104
2004-03-13,2.671980,1330.666667,10.916667,992.833333,187.037364,993.208333,118.628802,1595.791667,1245.916667,12.866667,51.533333,0.732296
2004-03-14,2.455313,1361.125000,9.637500,943.916667,150.787364,1001.291667,110.503802,1602.375000,1234.208333,16.012500,48.850000,0.849671

### Discretise continuous values with two bins, kmeans strategy and onehot-dense encoding

In [90]:

from sklearn.preprocessing import KBinsDiscretizer
#Discretizing continuous values with two bins, kmeans strategy and onehot-dense encoding
kbd = KBinsDiscretizer(n_bins=2,strategy='kmeans',encode='onehot-dense').set_output(transform='pandas')
dftransformed = kbd.fit_transform(df_grouped)
dftransformed.head()

,X00_0.0,X00_1.0,X01_0.0,X01_1.0,X03_0.0,X03_1.0,X04_0.0,X04_1.0,X05_0.0,X05_1.0,...,X08_0.0,X08_1.0,X09_0.0,X09_1.0,X10_0.0,X10_1.0,X11_0.0,X11_1.0,X12_0.0,X12_1.0
Date,,,,,,,,,,,,,,,,,,,,,
2004-03-10,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-11,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-12,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2004-03-13,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-14,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

###  Discretization/encoding generates 0/1 values; convert the binary values obtained into boolean, as requested by Apriori

In [91]:
dfapriori=dftransformed.astype(bool)
dfapriori.head()

,X00_0.0,X00_1.0,X01_0.0,X01_1.0,X03_0.0,X03_1.0,X04_0.0,X04_1.0,X05_0.0,X05_1.0,...,X08_0.0,X08_1.0,X09_0.0,X09_1.0,X10_0.0,X10_1.0,X11_0.0,X11_1.0,X12_0.0,X12_1.0
Date,,,,,,,,,,,,,,,,,,,,,
2004-03-10,True,False,False,True,True,False,True,False,True,False,...,False,True,False,True,True,False,False,True,True,False
2004-03-11,True,False,False,True,True,False,True,False,True,False,...,False,True,True,False,True,False,False,True,True,False
2004-03-12,False,True,False,True,False,True,False,True,True,False,...,False,True,False,True,True,False,True,False,True,False
2004-03-13,False,True,False,True,False,True,False,True,True,False,...,False,True,False,True,True,False,False,True,True,False
2004-03-14,False,True,False,True,True,False,False,True,True,False,...,False,True,False,True,True,False,True,False,True,False

###  Set the names of two columns generated by the discretisation of each attribute A to A_low, A_high (with discretisation/one-hot-encoding, each original column generates two columns, the first is for the low values, the second for the high values)

In [97]:
newcolnames = {}
for column in dftransformed.columns :
    colname = column[:3]
    if column.endswith('_0.0') : newcolnames[column] = colname + '_low'
    elif column.endswith('_1.0') : newcolnames[column] = colname + '_high'
    else : newcolnames[column] = column

dfrenamed = dftransformed.rename(columns=newcolnames)
dfrenamed.head()

,X00_low,X00_high,X01_low,X01_high,X03_low,X03_high,X04_low,X04_high,X05_low,X05_high,...,X08_low,X08_high,X09_low,X09_high,X10_low,X10_high,X11_low,X11_high,X12_low,X12_high
Date,,,,,,,,,,,,,,,,,,,,,
2004-03-10,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-11,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,...,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-12,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0
2004-03-13,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
2004-03-14,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0

### find a value of min_support such that the Apriori algorithm generates at least 8 frequent itemsets with at least 2 items, output the result

In [104]:
min_itemsets = 8
min_item_in_itemset = 2
# "Reasonable" range
support_range = list(np.arange(0.1, 0.001, -0.001))

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
min_support = 0
for s_value in support_range:
    print(f"Trying support value {s_value:.2f}")
    frequent_itemsets = apriori(dfrenamed, min_support = s_value, use_colnames = True)
    # Calculate the number of itemsets that contain at least `min_item_in_itemset` items
    # frequent_itemsets must contains al least min_itemsets itemsset , and every item set must contains al least min_item_in_itemset item
    itemsets_above_threshold = sum([len(itemset) >= min_item_in_itemset for itemset in frequent_itemsets.itemsets])
    if itemsets_above_threshold >= min_itemsets:
        min_support = s_value
        break
if min_support == 0:
    print("No itemset found! Try again with a bigger range!")
else:
    print(f"I've selected min_support = {min_support:.3f}, which produced , {len(frequent_itemsets)} itemsets, {itemsets_above_threshold} of which had more than {min_item_in_itemset} items")

Trying support value 0.10

C:\Users\giasa\AppData\Roaming\Python\Python312\site-packages\mlxtend\frequent_patterns\fpcommon.py:175: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

I've selected min_support = 0.100, which produced , 9035 itemsets, 9011 of which had more than 2 items

### find the minimum metric threshold such that at least 100 association rules are extracted from the frequent itemsets found and show the metrics used and the best 10 rules by descending confidence and support

In [110]:
metric_threshold_range = np.arange(1, 0.01, -0.01)
min_association_rule = 100
min_metric_threshold = 0
association_rule_found = 0
current_metric = "lift"

for metric_value in metric_threshold_range:

    rules = association_rules(frequent_itemsets, metric=current_metric, min_threshold=metric_value)
    if rules.shape[0] >= min_association_rule:
        association_rule_found = rules.shape[0]
        min_metric_threshold = metric_value
        break

if association_rule_found == 0:
    print("No association rule! Try again with a bigger range!")
else:
    print(f"I've selected metric {current_metric}  with metric_value = {metric_value:.2f}, which produced , {association_rule_found} association_rules")

I've selected metric lift  with metric_value = 1.00, which produced , 531482 association_rules

In [112]:
# Print the first n rules found, sorted by descending confidence and support
n_rule = 10
sorted_rules=rules.sort_values(by=['confidence','support'],ascending=False).reset_index(drop=True)
sorted_rules[:10]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(X03_high),(X04_high),0.485934,0.560102,0.485934,1.0,1.785388,1.0,0.213761,inf,0.855721,0.867580,1.0,0.933790
1,(X04_low),(X03_low),0.439898,0.514066,0.439898,1.0,1.945274,1.0,0.213761,inf,0.867580,0.855721,1.0,0.927861
2,"(X04_low, X00_low)",(X03_low),0.434783,0.514066,0.434783,1.0,1.945274,1.0,0.211275,inf,0.859729,0.845771,1.0,0.922886
3,"(X04_low, X09_low)",(X03_low),0.414322,0.514066,0.414322,1.0,1.945274,1.0,0.201333,inf,0.829694,0.805970,1.0,0.902985
4,"(X08_high, X03_high)",(X04_high),0.411765,0.560102,0.411765,1.0,1.785388,1.0,0.181134,inf,0.747826,0.735160,1.0,0.867580
5,"(X04_low, X05_low)",(X03_low),0.409207,0.514066,0.409207,1.0,1.945274,1.0,0.198847,inf,0.822511,0.796020,1.0,0.898010
6,"(X04_low, X09_low, X00_low)",(X03_low),0.409207,0.514066,0.409207,1.0,1.945274,1.0,0.198847,inf,0.822511,0.796020,1.0,0.898010
7,"(X03_high, X06_low)",(X04_high),0.404092,0.560102,0.404092,1.0,1.785388,1.0,0.177759,inf,0.738197,0.721461,1.0,0.860731
8,"(X04_low, X05_low, X00_low)",(X03_low),0.404092,0.514066,0.404092,1.0,1.945274,1.0,0.196362,inf,0.815451,0.786070,1.0,0.893035
9,"(X04_low, X05_low, X09_low)",(X03_low),0.396419,0.514066,0.396419,1.0,1.945274,1.0,0.192633,inf,0.805085,0.771144,1.0,0.885572